services:
  - type: web
    name: hrms-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn hrms.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: fseoi36268-vx@mr8yrrdjnauaqcti7na)w0esrv^5tt8_^uii
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: hrms-backend.onrender.com
      - key: DB_NAME
        fromDatabase:
          name: hrms-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: hrms-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: hrms-db
          property: password
      - key: DB_HOST
        fromDatabase:
          name: hrms-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: hrms-db
          property: port
      - key: CORS_ALLOWED_ORIGINS
        value: https://hrms-lite-fullstack.vercel.app

databases:
  - name: hrms-db
    databaseName: hrms_db
    user: hrms_user
    plan: free
